// Action types for user
export const EMPTY_AUTH = "EMPTY_AUTH";
export const AUTO_LOGIN = "AUTO_LOGIN";

export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_PROCESS = "SIGNUP_PROCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const UPDATE_PASSWORD_PROCESS = "UPDATE_PASSWORD_PROCESS";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_PROCESS = "FORGOT_PASSWORD_PROCESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const VERIFY_CODE_PROCESS = "VERIFY_CODE_PROCESS";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_FAIL = "VERIFY_CODE_FAIL";

export const SET_PASSWORD_PROCESS = "SET_PASSWORD_PROCESS";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";

export const LOGOUT = "LOGOUT";

export const UPDATE_INFO = "UPDATE_INFO";

//action type for category
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";

export const GET_FAVORITES_CAT = "GET_FAVORITES_CAT";
export const GET_FAVORITES_CAT_FAIL = "GET_FAVORITES_CAT_FAIL";
export const GET_FAVORITES_CAT_SUCCESS = "GET_FAVORITES_CAT_SUCCESS";
