// Action types
export const EMPTY_AUTH = "EMPTY_AUTH";

export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_PROCESS = "SIGNUP_PROCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const FORGOT_PASSWORD_PROCESS = "FORGOT_PASSWORD_PROCESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const VERIFY_CODE_PROCESS = "VERIFY_CODE_PROCESS";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_FAIL = "VERIFY_CODE_FAIL";

export const SET_PASSWORD_PROCESS = "SET_PASSWORD_PROCESS";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";
